-- NHẬP ID BỆNH NHÂN TÍNH TỔNG TIỀN KHÁM BỆNH
CREATE OR ALTER PROC TINH_CHECK_BILL
@ID_BN VARCHAR(10)
AS
BEGIN
	IF (SELECT P_BHYT FROM PATIENT WHERE P_ID = @ID_BN) = N'CÓ'
		BEGIN
			SELECT PRICE*0.3 FROM CHECK_BILL JOIN LAB_CHECK ON CHECK_BILL.LC_ID = LAB_CHECK.LC_ID WHERE P_ID = @ID_BN 
		END
	ELSE 
		BEGIN
			SELECT PRICE FROM CHECK_BILL JOIN LAB_CHECK ON CHECK_BILL.LC_ID = LAB_CHECK.LC_ID WHERE P_ID = @ID_BN
			
		END
END

EXEC TINH_CHECK_BILL @ID_BN = 'P02'


-- NHẬP ID BỆNH NHÂN TÍNH TỔNG TIỀN ĐƠN THUỐC
CREATE OR ALTER PROC TINH_PRESCRIPTION_BILL
@ID_BN VARCHAR(10)
AS
BEGIN
	IF (SELECT P_BHYT FROM PATIENT WHERE P_ID = @ID_BN) = N'CÓ'
		BEGIN
			SELECT SUM(TOTAL_PRICE)*0.3*1000 
			FROM BILL_DETAIL JOIN BILL_OF_PHARMACY ON BILL_DETAIL.BP_ID = BILL_OF_PHARMACY.BP_ID 
			JOIN PRESCRIPTION ON BILL_OF_PHARMACY.PR_ID = PRESCRIPTION.PR_ID JOIN PATIENT ON PRESCRIPTION.P_ID = PATIENT.P_ID
			WHERE PATIENT.P_ID = @ID_BN
		END
	ELSE
		BEGIN
			SELECT SUM(TOTAL_PRICE)*1000 
			FROM BILL_DETAIL JOIN BILL_OF_PHARMACY ON BILL_DETAIL.BP_ID = BILL_OF_PHARMACY.BP_ID 
			JOIN PRESCRIPTION ON BILL_OF_PHARMACY.PR_ID = PRESCRIPTION.PR_ID JOIN PATIENT ON PRESCRIPTION.P_ID = PATIENT.P_ID
			WHERE PATIENT.P_ID = @ID_BN
		END
END

EXEC TINH_CHECK_BILL @ID_BN = 'P11'


-- UPDATE ROOM_BILL
CREATE OR ALTER PROC UPDATE_DATEOUT 
@ID_BN VARCHAR(10)
AS
BEGIN
	DECLARE @DATE_IN DATE
	SET @DATE_IN = (SELECT TOP 1 RB_DATE_IN FROM ROOM_BILL JOIN IMPATIENT ON ROOM_BILL.I_ID = IMPATIENT.I_ID JOIN PATIENT ON IMPATIENT.P_ID = @ID_BN)
	UPDATE ROOM_BILL
	SET RB_DATE_OUT = CAST(GETDATE() AS DATE),
		RB_TOTAL_PRICE = (SELECT DATEDIFF(DAY, @DATE_IN, CAST(GETDATE() AS DATE)))*100000
	WHERE I_ID IN (SELECT ROOM_BILL.I_ID FROM ROOM_BILL JOIN IMPATIENT ON ROOM_BILL.I_ID = IMPATIENT.I_ID JOIN PATIENT ON IMPATIENT.P_ID = @ID_BN)
END

EXEC UPDATE_DATEOUT @ID_BN = 'P18'


-- TÌM PHÒNG KHÔNG CÓ BỆNH NHÂN
CREATE OR ALTER PROC ROOM_NO_PATIENT
AS
BEGIN
	SELECT R_NAME FROM ROOM WHERE R_ID NOT IN (SELECT R_ID FROM ROOM_BILL WHERE RB_DATE_OUT IS NOT NULL)
END

EXEC ROOM_NO_PATIENT


--ĐẾM SỐ BỆNH NHÂN Ở MỖI PHÒNG
CREATE OR ALTER PROC NUMBER_PATIENT
AS
BEGIN
	SELECT R_NAME, COUNT(I_ID) AS NUMBER_PATIENT
	FROM ROOM JOIN ROOM_BILL ON ROOM.R_ID = ROOM_BILL.R_ID
	WHERE RB_DATE_OUT IS NULL
	GROUP BY R_NAME
END

EXEC NUMBER_PATIENT
